services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - google-creds:/app/credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account-key.json
      - DATABASE_URL=postgresql://bq_metadata:bq_metadata_password@db:5432/bq_metadata
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=bq_metadata
      - POSTGRES_PASSWORD=bq_metadata_password
      - POSTGRES_DB=bq_metadata
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  google-creds:
    driver: local
  postgres_data:
    driver: local
